### ISSUE TITLE
Jen Dadd Continued Onboarding

### ISSUE THREAD

**Issue by jendadd** [jendadd/skills-introduction-to-github#2]
# Jen Dadd Continued Onboarding 

### LearnUpon Modules 🧠

- [x] Overview of the GitHub Platform Story [here](https://github.learnupon.com/enrollments/207583738/details)

> - [ ] The GitHub Platform Story: Sales Edition [here](https://github.learnupon.com/enrollments/207583737/details)
> - [ ] The GitHub Platform Story & Pitch Deck [here](https://github.learnupon.com/enrollments/207583739/details)

- [x] Platform Scenario Practice: Software and Digital [here](https://github.learnupon.com/enrollments/207583734/details)
- [ ] GHAS Fundamentals [here](https://github.learnupon.com/enrollments/207583679/details)
- [x] Revenue Play Guide: Lead with Copilot [here](https://github.learnupon.com/enrollments/207583736/details)

### Field Services 🖥

- [x] Review previously compiled leadership document [here](https://docs.google.com/document/d/13354m614i7wOSJmMi4NRZI8mpBCOZba2dIWIsrNUWXM/edit?usp=sharing)
- [x] Listen to Consumption Business Workshop via Alex Moyle Slack [here](https://github.zoom.us/rec/play/Px3_IEcnKavs1WfzPUZhNpNSofhLBNiOCmfWZSsCnc_CdpKLZ6-kvEYhPQfOzApT1dWLBJsV19q5lE-V.eRbTm3nnHe4xg3Wu?canPlayFromShare=true&from=share_recording_detail&continueMode=true&componentName=rec-play&originRequestUrl=https%3A%2F%2Fgithub.zoom.us%2Frec%2Fshare%2F4WVY6DQoW_m3AqO0IvaKCTeJPsA2hyAI74m6HNsNwzHAnWRNpnhmgNsWdx4r7PF-.ZHBWlgEMsTiCTKmQ)
- [x] Listen to 5+ Gong Calls with SEs

### Continued 1:1s 🤝

- [x] Complete all scheduled 1:1s with ELD
- [x] Complete all scheduled 1:1s with SE ICs
- [x] Complete all scheduled 1:1s with SE Leadership 

### Enablement 🌟

- [x] Review project board for individuals 
- [x] Complete first Snippet 
- [x] Review PMM materials [here](https://docs.google.com/spreadsheets/d/1iUwnYMpztI-9CzGIa6l4luNQuHmtEOy58rcsxeU4HFg/edit?usp=sharing)

**Comment by amoyle229** [comment]
Well done for creating your first issue

**Comment by jendadd** [comment]
## Week 3

### LearnUpon Modules 🧠

- [x] Revenue Play Guide: Increase Copilot Adoption [here](https://github.learnupon.com/enrollments/207583735/details)
- [x] Revenue Play Guide: Land new customers from Bitbucket Server [here](https://github.learnupon.com/enrollments/207583732/details)
- [x] Revenue Play Guide: Displace GitLab [here](https://github.learnupon.com/enrollments/207583733/details)
- [ ] GHAS Fundamentals [here](https://github.learnupon.com/enrollments/207583679/details)

### Field Services 🖥

- [x] Review previous onboarding documents across Field Services [here](https://github.com/github/solutions-engineering/tree/master/guides/onboarding)
- [x] Review SE-created documents for learning including [Fabulous Features Newsletter](https://github.com/github/corporate-solutions-engineering/discussions/categories/fabulous-features) which aims to summarize and provide context to the Revenue Weekly Updates
- [x] Listen to roadmap calls from the past
- [x] Listen to 5 more SE calls via Gong
- [x] Meet with Jamie Jones 
- [x] Continue to complete 1:1s scheduled for this week 

### GitHub Product Knowledge 📖

_Future: Onboarding Sessions scheduled_

**Comment by jendadd** [comment]
## Week 3

### LearnUpon Modules 🧠

- [ ] Revenue Play Guide: Increase Copilot Adoption [here](https://github.learnupon.com/enrollments/207583735/details)
- [ ] Revenue Play Guide: Land new customers from Bitbucket Server [here](https://github.learnupon.com/enrollments/207583732/details)
- [ ] Revenue Play Guide: Displace GitLab [here](https://github.learnupon.com/enrollments/207583733/details)
- [ ] GHAS Fundamentals [here](https://github.learnupon.com/enrollments/207583679/details)

### Field Services 🖥

- [ ] Review previous onboarding documents across Field Services [here](https://github.com/github/solutions-engineering/tree/master/guides/onboarding)
- [ ] Review SE-created documents for learning
- [ ] Listen to SE-led roadmap call 
- [ ] Listen to 5 more SE calls via Gong

### GitHub Product Knowledge 📖

_Future_
